[package]
name = "r-ddit_framework"
version = "0.1.0"
authors = ["JohannesThoren <45944438+JohannesThoren@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 
reqwest = "0.8.4" 
json = "*"